# Site settings
title: CHQLB's BLOG
email: chqlb@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Hope it would be helpful.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chqla15
github_username:  chqlb

# Build settings
markdown: kramdown
